# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rmysqldump}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Johan Eckerstr\303\266m"]
  s.date = %q{2009-12-06}
  s.default_executable = %q{rmysqldump}
  s.description = %q{Dumping MySQL databases on the Starkast servers}
  s.email = %q{johan@duh.se}
  s.executables = ["rmysqldump"]
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "bin/rmysqldump",
     "lib/rmysqldump.rb",
     "rmysqldump.conf"
  ]
  s.homepage = %q{http://github.com/jage/rmysqldump}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Dump MySQL databases}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mysql>, ["> 0.0.0"])
    else
      s.add_dependency(%q<mysql>, ["> 0.0.0"])
    end
  else
    s.add_dependency(%q<mysql>, ["> 0.0.0"])
  end
end

